const os = require("os");
console.log(os.arch());
console.log(os.hostname());
console.log(os.platform());
console.log(os.tmpdir());
console.log(os.type());
const freeMomery = os.freemem();
console.log(`${freeMomery/1024/1024/1024}`);
const totalMomery = os.totalmem();
console.log(`${totalMomery/1024/1024/1024}`);